### ISSUE TITLE
Replacement for jQuery

### ISSUE THREAD

**Issue by drewbarontini** [spellbook/spellbook#46]
This is more of a longterm goal, but I'd like to start building up our own version of a super-simplified jQuery to replicate any of the needed functionality. Essentially, we just need better interfaces for the vanilla JS way of doing things now.

From a top-level view, it would be composed of these things initially:

- Document ready
- Extending objects (could use Underscore)
- Selecting elements (class/id/selector)
- Next/previous/parent/find
- Add/remove class
- Has class
- Append/prepend/before/after
- Event listeners (add/remove)
- Ajax

Inspiration from : http://youmightnotneedjquery.com/

**Comment by johndjameson** [comment]
Filament Group already tackled this one: https://github.com/filamentgroup/shoestring

**Comment by drewbarontini** [comment]
Yeah, I'm aware of that one, but I kind of wanted to toy around with an even more simplified one to experiment with, but shoestring might work. I wouldn't add this into Spellbook itself, but would, instead, create a separate repo for it.

**Comment by drewbarontini** [comment]
Closing this.
